// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    clearLookupButton: string;
    searchContainer: string;
    searchIconContainer: string;
    searchInput: string;
}
export const cssExports: CssExports;
export default cssExports;
