// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    folder: string;
    monitor: string;
    qualityProfile: string;
    selectInput: string;
    volume: string;
    specialVersion: string;
}
export const cssExports: CssExports;
export default cssExports;
