// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string;
    added: string;
    banner: string;
    bannerGrow: string;
    bannerImage: string;
    cell: string;
    certification: string;
    checkInput: string;
    issueCountMonitored: string;
    issuesDownloadedMonitored: string;
    link: string;
    monitorNewIssues: string;
    publisher: string;
    overlayTitle: string;
    folder: string;
    ratings: string;
    totalSize: string;
    title: string;
    status: string;
    tags: string;
    year: string;
}
export const cssExports: CssExports;
export default cssExports;
