// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string;
    added: string;
    banner: string;
    bannerGrow: string;
    bannerImage: string;
    cell: string;
    certification: string;
    checkInput: string;
    issueCount: string;
    issueProgress: string;
    link: string;
    monitorNewItems: string;
    publisher: string;
    overlayTitle: string;
    path: string;
    ratings: string;
    releaseGroups: string;
    specialVersion: string;
    sizeOnDisk: string;
    title: string;
    status: string;
    tags: string;
    year: string;
}
export const cssExports: CssExports;
export default cssExports;
