// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    selectAllInput: string;
    selectAllInputContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
