// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    copyButton: string;
    descriptionList: string;
    legend: string;
}
export const cssExports: CssExports;
export default cssExports;
