// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    displayName: string;
    lastRun: string;
    nextRun: string;
    schedule: string;
}
export const cssExports: CssExports;
export default cssExports;
