// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    source: string;
    volumeId: string;
    issueId: string;
    webLink: string;
    webTitle: string;
    webSubTitle: string;
    fileTitle: string;
    success: string;
    actions: string;
    truncate: string;
}
export const cssExports: CssExports;
export default cssExports;
