// This file is automatically generated    : string;
// Please do not change this file!
interface CssExports {
    dragHandle: string;
    dragIcon: string;
    placeholder: string;
    placeholderAfter: string;
    placeholderBefore: string;
    isDragging: string;
    drag: string;
    priority: string;
    status: string;
    title: string;
    sourceName: string;
    size: string;
    speed: string;
    progress: string;
    actions: string;
}
export const cssExports: CssExports;
export default cssExports;
