// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string;
    creationDate: string;
    filename: string;
}
export const cssExports: CssExports;
export default cssExports;
