// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    enabled: string;
    indexer: string;
    name: string;
}
export const cssExports: CssExports;
export default cssExports;
