// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    group: string;
    groupHeader: string;
    pages: string;
    page: string;
    selected: string;
    image: string;
    caption: string;
    label: string;
    similarity: string;
    selectAllInputContainer: string;
    selectAllInput: string;
    selectedCount: string;
}
export const cssExports: CssExports;
export default cssExports;
