// Regular
import {
    faBookmark as farBookmark,
    faCalendar as farCalendar,
    faCircle as farCircle,
    faClock as farClock,
    faClone as farClone,
    faDotCircle as farDotCircle,
    faFile as farFile,
    faFileArchive as farFileArchive,
    faFileVideo as farFileVideo,
    faFolder as farFolder,
    faHdd as farHdd,
    faHeart as farHeart,
    faKeyboard as farKeyboard,
    faObjectGroup as farObjectGroup,
    faObjectUngroup as farObjectUngroup,
    faSquare as farSquare,
} from '@fortawesome/free-regular-svg-icons';

// Solid
import {
    faArrowCircleLeft as fasArrowCircleLeft,
    faArrowCircleRight as fasArrowCircleRight,
    faArrowUp as fasArrowUp,
    faArrowDown as fasArrowDown,
    faAsterisk as fasAsterisk,
    faBackward as fasBackward,
    faBan as fasBan,
    faBars as fasBars,
    faBolt as fasBolt,
    faBookmark as fasBookmark,
    faBookReader as fasBookReader,
    faBook as fasBook,
    faBug as fasBug,
    faCalculator as fasCalculator,
    faCalendarAlt as fasCalendarAlt,
    faCaretDown as fasCaretDown,
    faCheck as fasCheck,
    faCheckCircle as fasCheckCircle,
    faChevronCircleDown as fasChevronCircleDown,
    faChevronCircleRight as fasChevronCircleRight,
    faChevronCircleUp as fasChevronCircleUp,
    faCircle as fasCircle,
    faCircleDown as fasCircleDown,
    faCirclePlay as fasCirclePlay,
    faCloud as fasCloud,
    faCloudDownloadAlt as fasCloudDownloadAlt,
    faCodeCompare as fasCodeCompare,
    faCog as fasCog,
    faCogs as fasCogs,
    faCopy as fasCopy,
    faDesktop as fasDesktop,
    faDownload as fasDownload,
    faEllipsisH as fasEllipsisH,
    faExclamationCircle as fasExclamationCircle,
    faExclamationTriangle as fasExclamationTriangle,
    faExternalLinkAlt as fasExternalLinkAlt,
    faEye as fasEye,
    faFastBackward as fasFastBackward,
    faFastForward as fasFastForward,
    faFileArrowDown as fasFileArrowDown,
    faFileCircleQuestion as fasFileCircleQuestion,
    faFileExport as fasFileExport,
    faFileImage as fasFileImage,
    faFileInvoice as farFileInvoice,
    faFilter as fasFilter,
    faFlag as fasFlag,
    faFolderOpen as fasFolderOpen,
    faFolderTree as farFolderTree,
    faForward as fasForward,
    faHeart as fasHeart,
    faHistory as fasHistory,
    faHome as fasHome,
    faInfoCircle as fasInfoCircle,
    faLaptop as fasLaptop,
    faLevelUpAlt as fasLevelUpAlt,
    faListCheck as fasListCheck,
    faMedkit as fasMedkit,
    faMinus as fasMinus,
    faPause as fasPause,
    faPlay as fasPlay,
    faPlus as fasPlus,
    faPowerOff as fasPowerOff,
    faQuestion as fasQuestion,
    faQuestionCircle as fasQuestionCircle,
    faRedoAlt as fasRedoAlt,
    faRetweet as fasRetweet,
    faRocket as fasRocket,
    faRss as fasRss,
    faSave as fasSave,
    faSearch as fasSearch,
    faShareNodes as fasShareNodes,
    faSignOutAlt as fasSignOutAlt,
    faSitemap as fasSitemap,
    faSort as fasSort,
    faSortDown as fasSortDown,
    faSortUp as fasSortUp,
    faSpinner as fasSpinner,
    faSquareCheck as fasSquareCheck,
    faSquareMinus as fasSquareMinus,
    faStop as fasStop,
    faSync as fasSync,
    faTable as fasTable,
    faTags as fasTags,
    faTh as fasTh,
    faTheaterMasks as fasTheaterMasks,
    faThList as fasThList,
    faTimes as fasTimes,
    faTimesCircle as fasTimesCircle,
    faTrashAlt as fasTrashAlt,
    faUser as fasUser,
    faUserPlus as fasUserPlus,
    faVial as fasVial,
    faWrench as fasWrench,
} from '@fortawesome/free-solid-svg-icons';

// Icons
export const icons = {
    ACTIONS: fasBolt,
    ACTIVITY: farClock,
    ADD: fasPlus,
    ALTERNATE_TITLES: farClone,
    ADVANCED_SETTINGS: fasCog,
    ARROW_LEFT: fasArrowCircleLeft,
    ARROW_RIGHT: fasArrowCircleRight,
    ARROW_UP: fasArrowUp,
    ARROW_DOWN: fasArrowDown,
    BACKUP: farFileArchive,
    BLOCK: fasBan,
    BUG: fasBug,
    CALENDAR: fasCalendarAlt,
    CALENDAR_O: farCalendar,
    CARET_DOWN: fasCaretDown,
    CHECK: fasCheck,
    CHECK_INDETERMINATE: fasMinus,
    CHECK_CIRCLE: fasCheckCircle,
    CHECK_SQUARE: fasSquareCheck,
    CIRCLE: fasCircle,
    CIRCLE_DOWN: fasCircleDown,
    CIRCLE_OUTLINE: farCircle,
    CLEAR: fasTrashAlt,
    CLIPBOARD: fasCopy,
    CLOSE: fasTimes,
    CLONE: farClone,
    COLLAPSE: fasChevronCircleUp,
    COMPUTER: fasDesktop,
    CONVERT: fasCodeCompare,
    DANGER: fasExclamationCircle,
    DELETE: fasTrashAlt,
    DOWNLOAD: fasDownload,
    DOWNLOADED: fasDownload,
    DOWNLOADING: fasCloudDownloadAlt,
    DRIVE: farHdd,
    EDIT: fasWrench,
    ISSUE_FILE: farFileVideo,
    EXPAND: fasChevronCircleDown,
    EXPAND_INDETERMINATE: fasChevronCircleRight,
    EXPORT: fasFileExport,
    EXTERNAL_LINK: fasExternalLinkAlt,
    FATAL: fasTimesCircle,
    FILE: farFile,
    FILE_MISSING: fasFileCircleQuestion,
    FILTER: fasFilter,
    FLAG: fasFlag,
    FOOTNOTE: fasAsterisk,
    FOLDER: farFolder,
    FOLDER_OPEN: fasFolderOpen,
    GENERAL_FILES: fasFileImage,
    GENRE: fasTheaterMasks,
    GROUP: farObjectGroup,
    HEALTH: fasMedkit,
    HEART: fasHeart,
    HEART_OUTLINE: farHeart,
    HISTORY: fasHistory,
    HOUSEKEEPING: fasHome,
    IGNORE: fasTimesCircle,
    INFO: fasInfoCircle,
    INTERACTIVE: fasUser,
    KEYBOARD: farKeyboard,
    LIBGEN_FILE_SEARCH: fasFileArrowDown,
    LOGOUT: fasSignOutAlt,
    MANAGE: fasListCheck,
    MEDIA_INFO: farFileInvoice,
    MISSING: fasExclamationTriangle,
    MONITORED: fasBookmark,
    PUBLISHER: fasBook,
    NAVBAR_COLLAPSE: fasBars,
    NOT_AIRED: farClock,
    ORGANIZE: fasSitemap,
    OVERFLOW: fasEllipsisH,
    OVERVIEW: fasThList,
    PAGE_FIRST: fasFastBackward,
    PAGE_PREVIOUS: fasBackward,
    PAGE_NEXT: fasForward,
    PAGE_LAST: fasFastForward,
    PARENT: fasLevelUpAlt,
    PARSE: fasCalculator,
    PAUSED: fasPause,
    PENDING: farClock,
    PLAY: fasPlay,
    PREMIERE: fasCirclePlay,
    PROFILE: fasUser,
    POSTER: fasTh,
    QUEUED: fasCloud,
    QUICK: fasRocket,
    REFRESH: fasSync,
    REMOVE: fasTimes,
    RESTART: fasRedoAlt,
    RESTORE: fasHistory,
    REORDER: fasBars,
    ROOT_FOLDER: farFolderTree,
    RSS: fasRss,
    SAVE: fasSave,
    SCENE_MAPPING: fasSitemap,
    SCHEDULED: farClock,
    SCORE: fasUserPlus,
    SEARCH: fasSearch,
    TORRENT: fasShareNodes,
    VOLUME_CONTINUING: fasPlay,
    VOLUME_ENDED: fasStop,
    VOLUME_DELETED: fasExclamationTriangle,
    SETTINGS: fasCogs,
    SHUTDOWN: fasPowerOff,
    SORT: fasSort,
    SORT_ASCENDING: fasSortUp,
    SORT_DESCENDING: fasSortDown,
    SPINNER: fasSpinner,
    SQUARE: farSquare,
    SQUARE_MINUS: fasSquareMinus,
    SUBTRACT: fasMinus,
    SYSTEM: fasLaptop,
    TABLE: fasTable,
    TAGS: fasTags,
    TBA: fasQuestionCircle,
    TEST: fasVial,
    UNGROUP: farObjectUngroup,
    UNKNOWN: fasQuestion,
    UNMONITORED: farBookmark,
    UPDATE: fasRetweet,
    UNSAVED_SETTING: farDotCircle,
    VIEW: fasEye,
    WARNING: fasExclamationTriangle,
    WIKI: fasBookReader,
} as const;

export default icons;
