// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    addButton: string;
    addRemoteMapping: string;
    host: string;
    path: string;
    remotePathMappingsHeader: string;
}
export const cssExports: CssExports;
export default cssExports;
