// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    freeSpace: string;
    isMissing: string;
    path: string;
    pathContainer: string;
    selectedValue: string;
    volumeFolder: string;
}
export const cssExports: CssExports;
export default cssExports;
