// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    legend: string;
    title: string;
    subtitle: string;
}
export const cssExports: CssExports;
export default cssExports;
