// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    detailsIcon: string;
    folder: string;
    monitor: string;
    qualityProfile: string;
    seasonFolder: string;
    comics: string;
    comicsType: string;
}
export const cssExports: CssExports;
export default cssExports;
