// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    freeSpace: string;
    isMissing: string;
    isMobile: string;
    optionText: string;
    volumesFolder: string;
    value: string;
}
export const cssExports: CssExports;
export default cssExports;
