// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    body: string;
    defaultKind: string;
    inverse: string;
    tooltip: string;
    tooltipContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
