// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string;
    added: string;
    banner: string;
    bannerGrow: string;
    issueCountMonitored: string;
    issuesDownloadedMonitored: string;
    monitorNewIssues: string;
    monitored: string;
    volumeNumber: string;
    publisher: string;
    folder: string;
    releaseGroups: string;
    specialVersion: string;
    totalSize: string;
    title: string;
    status: string;
    year: string;
}
export const cssExports: CssExports;
export default cssExports;
