// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    center: string;
    panel: string;
    panelHeader: string;
    panelBody: string;
    signIn: string;
    formGroup: string;
    button: string;
    loginFailed: string;
}
export const cssExports: CssExports;
export default cssExports;
