// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    danger: string;
    defaultKind: string;
    disabled: string;
    info: string;
    pink: string;
    purple: string;
    success: string;
    warning: string;
}
export const cssExports: CssExports;
export default cssExports;
