// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    selectedContainer: string;
    selectedInput: string;
}
export const cssExports: CssExports;
export default cssExports;
