// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string;
    displayTitle: string;
    downloadIcon: string;
    dpi: string;
    filesize: string;
    indexerTitle: string;
    interactiveIcon: string;
    issueNumber: string;
    manualDownloadContent: string;
    match: string;
    matchIcon: string;
    pages: string;
    rejected: string;
    releaser: string;
    resolution: string;
    scanType: string;
    selectedSourceButton: string;
}
export const cssExports: CssExports;
export default cssExports;
