// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    issueFormat: string;
    path: string;
    previews: string;
    selectAllInput: string;
    selectAllInputContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
