// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    checkContainer: string;
    formatPreference: string;
    formatPreferenceContainer: string;
    dragHandle: string;
    dragIcon: string;
    isDragging: string;
    label: string;
    placeholder: string;
    placeholderAfter: string;
    placeholderBefore: string;
}
export const cssExports: CssExports;
export default cssExports;
