// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    actions: string;
    added: string;
    banner: string;
    bannerGrow: string;
    issueCount: string;
    issueProgress: string;
    monitorNewItems: string;
    publisher: string;
    folder: string;
    releaseGroups: string;
    volumeType: string;
    sizeOnDisk: string;
    title: string;
    status: string;
    year: string;
}
export const cssExports: CssExports;
export default cssExports;
