// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    row: string;
    imageContainer: string;
    inputContainer: string;
    buttons: string;
    modalHeader: string;
    modalHeaderContainer: string;
    refreshButton: string;
}
export const cssExports: CssExports;
export default cssExports;
