// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    folder: string;
    monitor: string;
    qualityProfile: string;
    seasonFolder: string;
    selectInput: string;
    volumes: string;
    volumesType: string;
}
export const cssExports: CssExports;
export default cssExports;
